name: GaG Stock Checker

on:
  schedule:
  # Run every 5 minutes between 6am - 9pm Mountain Time
  - cron: "*/5 * * * *"

  workflow_dispatch:

env:
  TZ: America/Denver

jobs:
  check-stock:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v5

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.11

    - name: Install Requirements
      shell: bash
      run: |
        pip install -r requirements.txt

    - name: Run Tool
      shell: bash
      run: |
        python src/main.py
      env:
        NTFY_NAME: ${{ secrets.NTFY_NAME }}
        JSTUDIO_API_KEY: ${{ secrets.JSTUDIO_API_KEY }}

    - name: Save Results
      uses: actions/upload-artifact@v4
      if: always() && (success() || failure() || cancelled())
      with:
        name: results
        path: |
          temp
          files
