name: GaG Stock Checker

on:
  schedule:
  # This schedule covers 12pm - 11:55pm UTC (6am-5:55pm MDT)
  - cron: "*/7 12-23 * * *"
  # This schedule covers 12am - 3:55am UTC (6pm - 9:55PM MDT)
  - cron: "*/7 0-3 * * *"

  workflow_dispatch:

jobs:
  check-stock:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v5

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.11

    - name: Install Requirements
      shell: bash
      run: |
        pip install -r requirements.txt

    - name: Run Tool
      shell: bash
      run: |
        python src/main.py
      env:
        NTFY_NAME: ${{ secrets.NTFY_NAME }}
        JSTUDIO_API_KEY: ${{ secrets.JSTUDIO_API_KEY }}

    - name: Save Results
      uses: actions/upload-artifact@v4
      if: always() && (success() || failure() || cancelled())
      with:
        name: results
        path: |
          temp
          files
